### ISSUE TITLE
Gnome default apps don't get affected by the theme

### ISSUE THREAD

**Issue by T4puSD** [vinceliuice/Jasper-gtk-theme#11]
The default apps of gnome (Files, Settings etc) don't get affected when I applied the theme out of the box. Though, I found a solution  `https://askubuntu.com/questions/1437958/nautilus-43-not-following-gtk-theme` which worked for me.

I saw this issue both in `Nobara 37 Official` Edition and `Manjaro Gnome` edition.

**Comment by vinceliuice** [comment]
Run: ./install.sh -l

**Comment by T4puSD** [comment]
Thank makes sense now. Thanks! :) 

It would be nice if this information was in the README itself.

I have created a pull request about it. You can merge if you are interested.
