### ISSUE TITLE
Electron Apps on Wayland have a big border when maximized.

### ISSUE THREAD

**Issue by RayJW** [vinceliuice/Jasper-gtk-theme#16]
When running an Electron app in Wayland mode, the apps display a huge border limiting the window size, when running maximized.

It might be theming related because with `Adwaita-dark` it works fine. However, I also tried with the `Dracula`, and `TokyoNight` GTK themes and they both display significantly smaller borders. I have attached a few screenshots to demonstrate.

I'm using `Jasper-Green-Dark-Compact` but it's the same with the light version.
![Screenshot from 2023-07-19 13-59-21](https://github.com/vinceliuice/Jasper-gtk-theme/assets/29835902/113cbfb0-df64-4add-ae17-1bf6c6bbad83)
![Screenshot from 2023-07-19 13-59-09](https://github.com/vinceliuice/Jasper-gtk-theme/assets/29835902/b399b052-8e56-430c-a570-310911fe7cd9)
![Screenshot from 2023-07-19 13-58-50](https://github.com/vinceliuice/Jasper-gtk-theme/assets/29835902/f4f12682-79e8-40d9-8e80-d1c700b608a9)

**Comment by vinceliuice** [comment]
What's your gnome version?

**Comment by RayJW** [comment]
> What's your gnome version?

The newest in Fedora 38, Gnome version 44.3 and the issue appears with all apps I've tried so far.

**Comment by RayJW** [comment]
I don't think this issue is reproducible any more.
