### ISSUE TITLE
Unable to install the theme on Fedora 38 even though I do everything right I suppose?

### ISSUE THREAD

**Issue by Astonishskagen** [vinceliuice/Jasper-gtk-theme#19]
Hello, I am using Fedora 38 with all the updates. I am still a Linux noob (using Linux for 6-7 months now) but I have always used your themes (WhiteSur) succesfully on Gnome43+ too. I downloaded this theme  and installed it with the script, the way I have always done because I find it easier. I went into the theme folder and:

./install.sh -t all -l

It finished installing on Gnome Tweaks, I selected the Jasper-Dark for Gnome shell and again Jasper-Dark for Legacy Apps (I should have kept the legacy apps untouched?) and my nautilus was themed with the light version of the theme even tho I use dark version. Well, I deleted the gtk-4.0 folder from ~/.config/ directory and went to the download directory of the Jasper Theme and copied the gtk-4.0 folder of the dark version into the /.config/ directory. The theme changed succesfuly to the dark version. When I restarted the computer, the theme came back to the default gnome theme. 

Well, then I deleted the gtk-3.0 and gtk-4.0 folders from /.config/ and then uninstalled the theme with the 

./install.sh -u
./install.sh -t all -u

script that I ran from inside the folder of downloaded Jasper theme. Then I went to the /.themes/ directory and deleted all the Jasper theme folders which were somehow still there after the uninstall script. Then this time I tried installing the theme without any options just with:

./install.sh -l 

script. Again the result was the same, first I had the light colored Nautilus theme from the Jasper theme, then I restarted the computer, and my theme went back to the default.

gnome-themes-extra
gtk-murrine-engine
sassc

are all installed on my system. I don't know what I am doing wrong here, could you please help?

Thank you!

**Comment by vinceliuice** [comment]
Did you installed any extension about theme style ? like : Material You Color Theming ?

**Comment by Astonishskagen** [comment]
Hello!

I apologize, in the meantime till you replied, I changed completely my set-up and went to Hyprland and I am using hyprland right now and I forgot about this thread.

I was not using Material you but I was using Custom Accent Colours extensions, this could be the reason? But I was not using it. Even though it was enabled, on Gnome Shell, I was using your theme.

**Comment by vinceliuice** [comment]
If it was enabled then it'll make a new `$HOME/.config/gtk-4.0/gtk.css` every time your start your desktop

**Comment by Astonishskagen** [comment]
Oh I get it, then most probably it was the issue. Thank you so much for pointing me to the right direction. At least, when I return to gnome, I know how to fix it now. :)
