### ISSUE TITLE
Strange black border

### ISSUE THREAD

**Issue by Hayao0819** [vinceliuice/Jasper-gtk-theme#2]
I found a border on Xfce4 Whisker menu. How can I fix it?
I downloaded theme from [here](https://www.gnome-look.org/p/1891521)

![image](https://user-images.githubusercontent.com/32128205/187214288-6c8ee63e-1d6d-4730-bd06-e606c97001a8.png)

**Comment by vinceliuice** [comment]
Open the Whisker menu appearance setting and set some opacity to the window
