### ISSUE TITLE
Notification is broken on Gnome 46

### ISSUE THREAD

**Issue by wolf-yuan-6115** [vinceliuice/Jasper-gtk-theme#25]
When I enabled this theme in shell, notification popout looks like this:

![Screenshot from 2024-04-21 21-10-42](https://github.com/vinceliuice/Jasper-gtk-theme/assets/58245644/f3c48456-196e-4c6b-8336-8e1909900cc1)

But instead this is what it should looks like:

![Screenshot from 2024-04-21 21-20-27](https://github.com/vinceliuice/Jasper-gtk-theme/assets/58245644/b27831c9-dbfc-4200-b4a4-d1f40c60abb3)

Also notification panel in clock drop down is also broken.

**Comment by wolf-yuan-6115** [comment]
In my test, all themes made by you has this issue.

**Comment by vinceliuice** [comment]
How did you install it, this is fixed already
![Screenshot from 2024-04-21 23-31-36](https://github.com/vinceliuice/Jasper-gtk-theme/assets/7604295/eeb9c8b0-63d5-4473-b98f-9f34571ded26)

**Comment by vinceliuice** [comment]
Download the last update and try again

**Comment by wolf-yuan-6115** [comment]
> Download the last update and try again

Interesting, let me try

**Comment by wolf-yuan-6115** [comment]
Well, it's indeed resolved. My repo is up to date but idk why it didn't apply.
