### ISSUE TITLE
Nasty bug for Nautilus headerbar on gnome 3.38

### ISSUE THREAD

**Issue by lb-d** [vinceliuice/Jasper-gtk-theme#6]
Never seen it before and have no clue what it is. It goes transparent and flimmers only on Jasper but is fine with other themes. Don't have blur my shell installed either. Strange stuff.

https://i.imgur.com/Mt01s1y.png

**Comment by vinceliuice** [comment]
Could you upload the pic here?

**Comment by lb-d** [comment]
![Mt01s1y](https://user-images.githubusercontent.com/40788882/189360992-f8e0694e-5d8d-4ab8-96dc-fcf6c35c3482.png)

Here you go.
